# Generated by Django 6.0.8 on 2026-08-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntentoFallido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.CharField(db_index=True, max_length=254)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("ocurrido_en", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "intento fallido",
                "verbose_name_plural": "intentos fallidos",
                "ordering": ["-ocurrido_en"],
            },
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="correo electrónico"),
        ),
    ]
