# Generated by Django 6.0.8 on 2026-08-06 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_email", models.CharField(blank=True, max_length=254)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("inicio_sesion", "Inicio de sesión"),
                            ("cierre_sesion", "Cierre de sesión"),
                            ("bloqueo_por_intentos", "Bloqueo por intentos fallidos"),
                            ("cambio_contrasena", "Cambio de contraseña"),
                        ],
                        max_length=40,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("detalle", models.CharField(blank=True, max_length=255)),
                ("ocurrido_en", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "registros de auditoría",
                "ordering": ["-ocurrido_en"],
            },
        ),
    ]
